### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by pulb** [pulb/mailnag#121]
As the title says. Progress should be tracked here.

**Comment by tikank** [comment]
What is the goal? Support only Python 3, or both Python 2 and 3?

What is the current status? Readme says Python 2, but what versions are supported, 2.7, 2.6, 2.5,...?

**Comment by pulb** [comment]
The goal is to support python3 exclusively. I believe Mailnag currently requires Python 2.7.

Am 3. September 2016 16:48:27 MESZ, schrieb Timo Kankare <notifications@github.com>:

**Comment by knurd** [comment]
What is the current status of the Python3 port? Just wondering, because Fedora in its devel branch dropped on of the optional deps of mailnag (python-notify) because is has not been ported to python3; sooner or later this fate will hit mailnag itself, too, if it's not ported.

**Comment by pulb** [comment]
Hey @knurd, sorry for the late reply. Unfortunately, nothing happened regarding python3 porting so far. But thanks for that information, I hope I'll find some time in the near future to work on it.

**Comment by razerraz** [comment]
I'm currently working on mailnag's python3 port, since I'm using it for decades and python2 support ending soon.
It's actually running fine, considering I don't have tested all features yet.
My first task was to have PEP8 py3 compliant basecode.  This was the most time consuming task, and it remove ability to PR things : it include tabs to spaces conversion, so every line of code is affected...
Then I worked on py3 conversion without taking care of keeping py2's (ihmo, it's a pain in the ass to do without any good reasons since py2 will RIP soon), and it was mostly an easy task
The last thing is that I don't really want to use this git service, as I consider it _to big to be trusted_. It's available here ::
https://framagit.org/razer/mailnag

cheers

**Comment by pulb** [comment]
Hey, this is awesome news!

Many thanks for your very appreciated efforts, I'll have a closer look as soon as I find time.

Best regards
Patrick

Am 22. Februar 2019 11:54:05 MEZ schrieb razerraz <notifications@github.com>:
>I'm currently working on mailnag's python3 port, since I'm using it for
>decades and python2 support ending soon.
>It's actually running fine, considering I don't have tested all
>features yet.
>My first task was to have PEP8 py3 compliant basecode.  This was the
>most time consuming task, and it remove ability to PR things : it
>include tabs to spaces conversion, so every line of code is affected...
>Then I worked on py3 conversion without taking care of keeping py2's
>(ihmo, it's a pain in the ass to do without any good reasons since py2
>will RIP soon), and it was mostly an easy task
>The last thing is that I don't really want to use this git service, as
>I consider it _to big to be trusted_. It's available here ::
>https://framagit.org/razer/mailnag
>
>cheers
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pulb/mailnag/issues/121#issuecomment-466357527

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by razerraz** [comment]
Well, it's a nice project with human size, easy to understand (since it was well designed) basecode.
Just a couple of things are annoying me, so I goes deep into a big rewriting / refactoring, making things more easiest to maintain I guess
I will sync the repo soon with something relevant
Cheers

**Comment by pulb** [comment]
I'm not sure if it is well designed since it was originally forked from another project (popper) and there are still a few places I am not happy with :) But nice to see someone else interesed in the project. Please keep me updated :)

**Comment by razerraz** [comment]
Well as i said before I ran into major refactoring, at a point near to rewriting.
Core stuff is near from being ready, but a lot of the ui part need to be rewrited I fear, but I haven't got really into it right now.
To be a little more precise I rewrited accounts model, mails conversion, dbus is now part of core code instead of plugin, and I wonder right now if making the same with GOA is a good idea or not.
I'll try to find the time to sync, then you will see my work soon
cheers

**Comment by razerraz** [comment]
Work in progress available here : 
https://framagit.org/razer/mailnag/tree/devel

Hope you will not scream too loud seeing that ;)

**Comment by pulb** [comment]
@razerraz: Thanks! Will have a look asap :)

**Comment by knurd** [comment]
FWIW: Fedora is planing to kick Python2 (and thus mailnag, if the python3 port is not getting forward) out in the next few months:
https://bugzilla.redhat.com/show_bug.cgi?id=1737817
https://fedoraproject.org/wiki/Changes/F31_Mass_Python_2_Package_Removal (Fedora 31, due in Oct 2019)
https://fedoraproject.org/wiki/Changes/RetirePython2 (Fedora 32, due May 2020)

**Comment by razerraz** [comment]
Well I'm currently working on it, should be beta ready at the end of the month.
Since it's near from a complete rewrite, and to avoid any confusions, I'm thinking about renaming the project. I'll keep you informed about my progress
cheers

**Comment by razerraz** [comment]
I have something right now that could be a good working base even if there is still a lot of work to do ::
https://framagit.org/razer/bubblemail

I miss time and skills, and need help for artwork, packaging and translation

**Comment by pulb** [comment]
Python 3 migration is work in progress, see https://github.com/pulb/mailnag/tree/python3-migration.
Pull requests (one per fixed problem please) are very appreciated!

**Comment by knurd** [comment]
Great, much appreciated! Just wondering: How much WIP is this? Is it basically usable already?

**Comment by pulb** [comment]
I just started porting last weekend. After an hour or so mailnag-config was already running with python3. I don't know how much work is left to get the daemon running - after fixing a few runtime errors a few more surfaced :) I've got the feeling it's pretty straightforward though. I'll let you know if it's ready for testing :)

**Comment by pulb** [comment]
@razerraz,

unfortunately you decided to fork this project to a foreign repo and rewrote the whole code base on your own, without talking to upstream whether all those changes are even desirable (integrating GOA into the core project for example is not, as it's meant to be desktop-independent). That's not exactly how contributing to open source projects works.

Our plan is to port to python3 first, then do some refactoring where needed. These are two independent steps that should not be mixed.

All ranting aside, some of your changes indeed look interesting and you seem to be very motivated to improve this project, so if python3 porting is completed, I'd be very happy if we can cheery-pick and integrate some features from your fork :)

**Comment by razerraz** [comment]
Ok, you are free to do whatever you want as I do, like malking the kind of shortcuts I read here :
I don't consider any fork unfortunate
I don't judge guys without knowing them, I contribute to OSP since twenty years, even if I can't prove it since it's always as anonymous wirh different names. Sometimes I feel that rewriting parts are worth doing. I don't intend to be always right, changes can follow or not, I don't judge anything.

So, do whatever you want, but please stop trying to explain to me what is unfortunate and what is contributing to OSS

**Comment by pulb** [comment]
Please don't feel offended, I really appreciate your efforts. It's just that I don't feel like replacing the entired code with code by someone else at once. It's very hard to review all those changes, let alone to understand the reasons behind it. I'd rather like the workflow of integrating discrete features one by one, preferably through pull requests of descriptive commits.

When I said I'd be very happy if we can  integrate features from your fork, I was of course hoping that "we" includes you as well.




Am 22. Oktober 2019 08:59:10 MESZ schrieb razerraz <notifications@github.com>:

**Comment by razerraz** [comment]
As most guys I write software as an hobby, and I recon that sometimes I need to get a whole new picture to be satisfied in the task. Just before looking at your project, I have done a lot of work on projects where I had to deal with old and ugly code parts. I just needed fresh air.
If you read me carefully, I never mention anything about replacing all the code at once. As you mention, just having the code running on python3 is not a big deal, then we have the historic branch and a more cutting edge one.

**Comment by tikank** [comment]
Hi @pulb. I made some time ago experiments to run mailnag unit tests with python 3. I pushed changes to branch https://github.com/tikank/mailnag/tree/py3-unit-tests . Take a look and use them if you wish. I have not (yet) tried tests with your migration branch.

**Comment by pulb** [comment]
@razerraz Yes, I can understand your motivation for rewriting code, I often feel the same. I hope we can start integrating pieces from your fork soon.

@tikank thanks! will have a look as soon as i find time.

**Comment by razerraz** [comment]
I take time to write further explanations on my choice to mostly rewriting everything during my work flow. Since right know you seems motivated to work on mailnag, it should perhaps be some kind of inspirations doing it besides explaining my choices.
https://framagit.org/razer/bubblemail#history-and-mailnag-differences

Regards

**Comment by tikank** [comment]
Hi @pulb. Added also test coverage report. It seems that 1/4 of the code is covered (in some way) by tests.
See https://github.com/tikank/mailnag/compare/py3-unit-tests...tikank:py3-test-coverage

**Comment by pulb** [comment]
@razerraz thanks for those explanations. I agree with you in many points, esp. that dbus should be moved to core. I already replaced some small broken parts in the migration branch with code from you.

@knurd I'm running the python3-migration branch here and it works pretty fine now.

@tikank: Thanks, good to know!

**Comment by razerraz** [comment]
Great news you achieve to use parts of my work. 
Besides, as you probably know, libgnome-keyring is deprecated since a while now, and all parts of gnome desktop have already switched to the successor, libsecret.
This is on top of my todo list, first investigating about potential regressions it will lead to using non gnome desktop environment, and choose to implement it or another keyring tool accordingly.
I feel it's not so much differences in this part of the code between both projects, then you should be able to integrate my work on that I hope

**Comment by pulb** [comment]
Nice to hear that! There's also a long outstanding mailnag issue regarding libsecret migration :)

https://github.com/pulb/mailnag/issues/114

**Comment by pulb** [comment]
@tikank results of all your unittests are green, so it seems that at least 1/4 of the code is working as expected XD

**Comment by knurd** [comment]
> @knurd I'm running the python3-migration branch here and it works pretty fine now.

Thx, switched to it locally now as well. I might push this to Fedora rawhide (Fedora devel branch, which is prepping Fedora 32 right now, which is about to get released in half a year from noway) if that's okay for you, as python2 packages are scheduled to get removed there in mid November.

**Comment by pulb** [comment]
@knurd Great to hear that! Yes, I guess now is a good time to push it to rawide to make sure it's available and thoroughly tested in the upcoming Fedora 32 release. I've also got the feeling it's pretty stable already.

**Comment by knurd** [comment]
> now is a good time to push it to rawide […]

Done, will be in the next push. TWIMC, here is the spec file:
https://src.fedoraproject.org/rpms/mailnag/blob/master/f/mailnag.spec

BTW, had to do two things two shut up complains from rpmlint:
```
# make python3 explicit
sed -i 's_#!.*/usr/bin/env.*python.*_#!%{_bindir}/python3_' $(find . -name '*.py')
```
and
```
# fix "non-executable-script" errors
chmod 755 $RPM_BUILD_ROOT/%{python3_sitelib}/Mailnag/{__init__.py,common/imaplib2.py}
```

**Comment by pulb** [comment]
@knurd Many thanks! The two issues you mentioned are fixed now.

**Comment by knurd** [comment]
> @knurd Many thanks! The two issues you mentioned are fixed now.

Great, heading towards rawhide now.

Side note: I see you increased the version number to 2.0. That made me wonder: why not use this occasion to rename "mailnag" to "mailnagd" and "mailnag-config" to "mailnag"? That would 
* get rid of another (minor) rpmling warning (mailnag.noarch: W: devel-file-in-non-devel-package /usr/bin/mailnag-config),
* is more in line what users expect (at least IMHO), and 
* would likely finally fix the last remaining detail discussed in Issue 122 (gnome-software shows mailnag as Mailnag-Konfigurieren in locale de_DE

**Comment by pulb** [comment]
@knurd yes, the 2.0 release is good chance to introduce radical changes like this. I'll include this renaming in the upcoming release.

**Comment by pulb** [comment]
The python3-migration branch has been merged in master.
